name: Python package

on: [push]

jobs:  
  build:
  
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - uses: actions/checkout@v2
    - name: Setup Python # Set Python version
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    # Install pip and pytest
    - name: Unpack certificates
      env:
        GPG_PASS: ${{ secrets.GPG_PASS }} 
      run: |
        pushd `find . -type d -name "certs"`
        gpg --quiet --batch --yes --decrypt --passphrase="$GPG_PASS" --output certs.tar certs.tar.gpg
        tar xf certs.tar
        echo "Files under $(pwd):"
        ls -lht *
        popd
        echo "Back to $(pwd)"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test with pytest
      env:
        WEBSENTRY_KAFKA_TOPIC: sitecheck-test
        WEBSENTRY_KAFKA_CAFILE: ./certs/ca.pem
        WEBSENTRY_KAFKA_CERTFILE: ./certs/service.cert
        WEBSENTRY_KAFKA_KEY: ./certs/service.key
        WEBSENTRY_KAFKA_HOSTS: kafka-tomekbawej-2d43.aivencloud.com:19663
        WEBSENTRY_CONSUMER_ENABLE_DAEMON: 0
        WEBSENTRY_INTERVAL: -1
        WEBSENTRY_DATABASE_NAME: websentry-test
        WEBSENTRY_DATABASE_HOST: pg-tomekbawej-2d43.aivencloud.com
        WEBSENTRY_DATABASE_PORT: 19661
        WEBSENTRY_DATABASE_USER: websentry-test
        WEBSENTRY_DATABASE_PASSWORD: ${{ secrets.DB_PASS }}
        WEBSENTRY_SITES: https://google.com,http://something.that.does.not.exist
      run: |
        pytest test --doctest-modules --junitxml=junit/test-results-${{ matrix.python-version }}.xml --cov=websentry
    - name: Upload pytest test results
      uses: actions/upload-artifact@v2
      with:
        name: pytest-results-${{ matrix.python-version }}
        path: junit/test-results-${{ matrix.python-version }}.xml
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
